name: tic_tac_toe
homepage: https://tic-tac-toe.marchello.cf
description: Tic-tac-toe online

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  socket_io_client: ^0.9.9
  google_fonts: ^0.3.10
  material_design_icons_flutter: ^4.0.5045
  url_launcher: ^5.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
